<a href="https://colab.research.google.com/github/d-h-k/MLPy_workspace/blob/master/chp1_1_dhkim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 31 - numpy example

In [2]:
import numpy as np
x = np.array([[1,2,3], [4,5,6]])
print("x:\n",x)


x:
 [[1 2 3]
 [4 5 6]]


# 32 - scipy example

In [3]:
from scipy import sparse

eye = np.eye(4)
print("Numpy array:\n", eye)


Numpy array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
